Support Rails 5.1
activeadmin/inherited_resources pull request #433
Opened 2017-04-28 08:37 UTC by maschwenk

Rails 5.1 release has been officially cut http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/

2017-04-28 13:09 UTC, varyonic requested changes

2017-04-28 13:09 UTC, varyonic commented on .travis.yml
>      - rvm: 2.1.9
Needs
```
    - rvm: 2.1.9
      gemfile: test/gemfiles/Gemfile-Rails-5-1
```

2017-04-28 13:14 UTC, timoschilling commented on CHANGELOG
> +# Version 1.8.0
The dependency relax isn't a minor change, so we will release it under `1.7.2`

2017-04-28 13:15 UTC, timoschilling commented on lib/inherited_resources/version.rb
> +  VERSION = '1.8.0'.freeze
please don't make a version bump in a PR

2017-04-28 16:43 UTC, maschwenk commented on CHANGELOG
> +# Version 1.8.0
I assume you mean `major` change. Also, should I leave the changelog alone like the `version.rb` below? Just keep the actual code changes?

2017-04-28 21:51 UTC, rafaelfranca approved these changes

2017-04-29 00:13 UTC, varyonic commented on inherited_resources.gemspec
> +  s.add_dependency("actionpack", ">= 3.2", "< 5.2")
Should this be "< 5.2.x"?  < 5.1 was compatible with 5.1.rc2 but not 5.1.0 which was why we did not update sooner.

2017-04-29 00:13 UTC, varyonic approved these changes

2017-04-29 02:07 UTC, rafaelfranca commented on inherited_resources.gemspec
> +  s.add_dependency("actionpack", ">= 3.2", "< 5.2")
:+1:

2017-05-01 20:50 UTC, rafaelfranca commented
has_scope 0.7.1 was released

2017-05-01 21:35 UTC, deivid-rodriguez commented
I restarted the build and it installed fine, but the tests didn't pass. So it seems that there's actual work to be done here... :(

2017-05-01 21:50 UTC, maschwenk commented
Ahh yes. Looks like the Rails 5.0 change about putting all params in a params hash. Will fix when home.

2017-05-02 07:42 UTC, Empact commented on inherited_resources.gemspec
> +  s.add_dependency("railties", ">= 3.2", "< 5.2.x")
I don't think you want ".x" here.

2017-05-02 07:47 UTC, maschwenk commented on inherited_resources.gemspec
> +  s.add_dependency("railties", ">= 3.2", "< 5.2.x")
see https://github.com/activeadmin/inherited_resources/pull/433#discussion_r114039528

2017-05-02 09:22 UTC, maschwenk commented
Phew! more involved than I had suspected. I'm pretty new to working with this backwards compat. stuff.

2017-05-02 13:12 UTC, varyonic approved these changes

2017-05-02 13:20 UTC, deivid-rodriguez commented
Fantastic work @maschwenk, I don't have time to look at the diff right now, but the green checks look great! :)

2017-05-02 15:08 UTC, deivid-rodriguez approved these changes
Had a quick look and looks good to me. Not really aware of all the test class changes in https://github.com/activeadmin/inherited_resources/pull/433/commits/34d8fde5b3d6cee676660f5040935b53d2ee3c69, but they seem to be confirmed by the passing build. In any case, I'm 100% sure Rafael knows this stuff and can confirm :)

2017-05-02 17:53 UTC, rafaelfranca approved these changes

2017-05-02 18:09 UTC, merged

2017-05-02 18:11 UTC, deivid-rodriguez commented
Went ahead and merged this. Only pending a release! :tada:

2017-05-02 18:28 UTC, varyonic commented
Thanks @deivid-rodriguez Bump version and `rake release` is down to @rafaelfranca or @timoschilling

2017-05-02 18:57 UTC, timoschilling commented
I will do it